blank_issues_enabled: true
contact_links:
  - name: "💥 Bug Report"
    url: https://github.com/vikejs/vike/issues/new/choose
    about: "Report bugs at Vike's repository instead."
  - name: "✨ Feature Request"
    url: https://github.com/vikejs/vike/issues/new/choose
    about: "Suggest features at Vike's repository instead."
  - name: "🙏 Help & Questions"
    url: https://github.com/vikejs/vike/discussions/new?category=help-questions
    about: "[GitHub Discussions] Get official help from Vike maintainers."
  - name: "🗨️ Other"
    url: https://github.com/vikejs/vike/discussions/new?category=other
    about: "[GitHub Discussions] Anything else: ideas, feedback, complaints, appreciation, ..."
  - name: "💬 Chit-chat"
    url: https://discord.com/invite/hfHhnJyVg8
    about: "[Discord] Casual conversation with the community."
